### ISSUE TITLE
Failing scripts should stop the job

### ISSUE THREAD

**Issue by brechtm** [jannekem/run-python-script-action#1]
Currently, when the Python script fails, due to an unhandled exception for example, the workflow will continue executing the next step.

Thanks for this useful action!

**Comment by jannekem** [comment]
Hey, thanks for opening an issue!

I added some error handling to the action so it should now fail properly if there are errors. I also added `stdout` and `stderr` as outputs from the action that you may find useful.

**Comment by brechtm** [comment]
That was quick!

Would it be possible to show the output (both stderr and stdout) in the job log as well?

**Comment by jannekem** [comment]
I think it should already do that. Maybe the example in the documentation was confusing?

**Comment by brechtm** [comment]
> I think it should already do that. Maybe the example in the documentation was confusing?

I was confused, but it had nothing to do with the documentation. 😄
I'm using run-python-script-action to set outputs for a step using "::set-output" and I didn't see these in the log. I think GitHub Actions simply filters these lines out of the log, which confused me.
