### ISSUE TITLE
Add access to context information 

### ISSUE THREAD

**Issue by postlund** [jannekem/run-python-script-action#5]
Is it possible to add support for accessing context information, like the `github` instance? I need to access data in it that is too large to store in an environment variable and that might contain characters that aren't escaped, so it's really difficult to deal with the data in a shell script (I.e. in `run`).

**Comment by jannekem** [comment]
Sorry for the late response! The way that GitHub Actions internally passes data is through environment variables, so I don't think that it would help much. Also, I didn't find a straight-forward way to expose the `github` context. If you have large amounts of data then that should probably be stored in a temporary file.
